### PR TITLE
Fix bb bot pr template

### PR DESCRIPTION
**Pull request by JounQin**
See https://github.com/mdx-js/mdx-analyzer/pull/361#issuecomment-1848349276

### CODE REVIEW

**Comment by wooorm** [comment]
I think there should particularly be a comment with an ID: `<!--do not edit: $name-->`.
The sections are not needed. If remco wants to use custom templates, that should work.
@remcohaszing, what is the reason you have custom templates here? What do you want differently?

**Comment by JounQin** [comment]
There are contents different with unified.

```md
<!--
Read the [contributing guidelines](https://mdxjs.com/community/contribute/).
We are excited about pull requests, but please try to limit the scope, provide a general description of the changes, and remember, it's up to you to convince us to land it.
If this fixes an open issue, link to it in the following way: `Closes GH-123`.
New features and bug fixes should come with tests.
P.S. have you seen our support and contributing docs?
https://mdxjs.com/community/support/
https://mdxjs.com/community/contribute/
-->
```

**Comment by wooorm** [comment]
That seems to be equivalent to https://raw.githubusercontent.com/mdx-js/.github/main/.github/pull-request-template.md?

**Comment by wooorm** [comment]
ohhh, huh

**Comment by wooorm** [comment]
Sorry, I thought this was a PR to mdx-js/mdx-analyzer.

This should all work. Not sure why it suddenly failed. Maybe GH changed something

**Comment by wooorm** [comment]
Yup, you’re right. BB was never enabled on this org. So we’ve never seen it respond yet.

Here bb infers that the template is wrong! https://github.com/mdx-js/mdx-analyzer/actions/runs/7150409022/job/19473648743?pr=361#step:2:8

**Comment by JounQin** [comment]
> This should all work. Not sure why it suddenly failed. Maybe GH changed something

I don't understand what's the meaning, GH is just working as expected, we are just missing these sections in `mdx-js/.github/.github/pull-request-template.md`? So bb bot complains some required content missing.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
thank you!

**Comment by JounQin** [comment]
> Yup, you’re right. BB was never enabled on this org. So we’ve never seen it respond yet.
> 
> Here bb infers that the template is wrong! https://github.com/mdx-js/mdx-analyzer/actions/runs/7150409022/job/19473648743?pr=361#step:2:8

I think the bb bot should throw instead of just warning, how do you think?

**Comment by wooorm** [comment]
Sure but it’s just a bunch of hacky buggy scripts that works well enough for now, I wouldn’t put time in it!

**Pull request merged**
